### ISSUE TITLE
Why does `Applicative (StateT s f)` instance require `Monad f` bound?

### ISSUE THREAD

**Issue by ktt3ja** [data61/fp-course#134]
The instance implementation for [Applicative (StateT s f)](https://github.com/NICTA/course/blob/a9571e99d559a81039d5c49684afc9b696aad0f4/src/Course/StateT.hs#L73) only needs me to use the `pure` function. Even the doc states "given a `Applicative f`". Yet, if I were to change the bound `Monad f` to `Applicative f`, I'd get the following error:

```
src/Course/StateT.hs:66:10:
    Could not deduce (Bind f)
      arising from the superclasses of an instance declaration
    from the context (Applicative f)
      bound by the instance declaration at src/Course/StateT.hs:66:10-50
    Possible fix:
      add (Bind f) to the context of the instance declaration
    In the instance declaration for `Applicative (StateT s f)'
```

How does this error come about?

**Comment by thejohnfreeman** [comment]
Can you offer an implementation of `<*>` for `StateT s f` that only uses `pure` and `<*>` for `f`? I'm not sure it's possible, because the function within a `StateT` is essentially monadic. Consider the signature of `<*>`:

```haskell
StateT g <*> StateT h = ...
-- g :: s -> f (a -> b, s)
-- h :: s -> f (a, s)
-- g and h have signatures like that of the left argument of >>=
```

We need to apply `g` and `h` to get the function and argument respectively. We cannot apply them to the same state, though, or we will have to drop one of the two intermediate states, since the state type `s` is not a monoid:

```haskell
-- fst drops the intermediate state from (g s) and mapFst uses the intermediate state from (h s)
StateT g <*> StateT h = StateT $ \s -> (mapFst . fst) <$> g s <*> h s
  where mapFst f (x, s) = (f x, s)
```

The intermediate state is locked within an applicative in the result of `g s`, and we want to thread it through `h`. That sequencing implies to me that we need `f` to be a monad, and in fact, the [`Applicative` instance for `StateT` in the transformers package](https://hackage.haskell.org/package/transformers-0.4.3.0/docs/Control-Monad-Trans-State-Lazy.html#t:StateT) requires `f` to be a monad, and [its implementation of `<*>`](https://hackage.haskell.org/package/transformers-0.4.3.0/docs/src/Control-Monad-Trans-State-Lazy.html#line-184) uses the monadic function `ap`.

**Comment by rgrover** [comment]
@thejohnfreeman, is the following parallel implementation also valid? Note: the order in which `g` and `h` receive the `s` (or `s'`) argument has been reversed. 

```Haskell
    (<*>) :: StateT s m (a -> b) -> StateT s m a -> StateT s m b
    StateT (g :: s -> m (a -> b, s)) <*> StateT (h :: s -> m (a, s)) =
        StateT $ \s -> do
            (x, s') <- h s
            (f, s'') <- g s'
            return (f x, s'')

```
