### ISSUE TITLE
How to use provided nix files?

### ISSUE THREAD

**Issue by wizzup** [data61/fp-course#215]
I am on NixOS.

There are `nix` expressions provided.

    $ ls *.nix
    default.nix  fp-course.nix  shell.nix

But when I try to build or using the shell, I got following error:

    [wizzup@ fp-course] (master) 
    $ git rev-parse HEAD
    49c3e89187096554c05f96de3b30ad7dbd14f3e3
    [wizzup@ fp-course] (master) 
    $ nix-build 
    error: attribute ‘tasty-discover_3_0_2’ missing, at /data/learn/fp-course/default.nix:15:41
    (use ‘--show-trace’ to show detailed location information)
    [wizzup@ fp-course] (master) 
    $ nix-shell 
    error: attribute ‘tasty-discover_3_0_2’ missing, at /data/learn/fp-course/default.nix:15:41
    (use ‘--show-trace’ to show detailed location information)
    [wizzup@ fp-course] (master)

**Comment by wizzup** [comment]
I think I fix it, now I can use following step

    $ nix-shell
    
    [fp-course:/data/learn/fp-course]
    $ cabal test 

please see af9b16a for changes.

**Comment by dalaing** [comment]
I just pushed my own attempt at a change for this.

We haven't pinned a version of nixpkgs, since we want our Hydra instance to let us know when changes to nixpkgs are causing trouble.  On the other hand, the stable branch of nixos-17.03 still needs tasty-discover_3_0_2 for everything to work out for those folks.  So there's a bit of juggling things around to try to get a setup that works for multiple GHC versions and multiple nixpkgs versions.

I think I've made the test for whether that is necessary a bit more robust now - if you could try the latest version from master and let me know if it works, that would be great.

**Comment by wizzup** [comment]
Your fix 5959d is working. There are no error.

But I think `cabal` should be included in `nix-shell` to make it self-contained. I usually don't have neither `ghc` nor `cabal-install` outside my haskell shell.
