### ISSUE TITLE
Please reinstate course.cabal.

### ISSUE THREAD

**Issue by paul-snively** [data61/fp-course#376]
The removal of course.cabal causes the project to be non-functional with the haskell-ide-engine.

**Comment by gwils** [comment]
The primary purpose of the course repo is to be run in a classroom setting, in person. The way we run the course is with a basic text editor and `ghci`.
We wanted the simplest build toolchain possible. Recently we've made the course use its own simple test framework in order to remove all external dependencies. This has allowed us to remove the cabal file, since it is no longer needed to provide test dependencies.
We want to remove as many files and directories as possible from the repo, as they are extra surface area for distraction and confusion.

Regarding haskell-ide-engine, unfortunately supporting that tool is not a goal of the course. If you'd like some kind of IDE-ish functionality, `ghcid` works well and has eg. a VS Code integration. We don't explicitly support `ghcid` either, but it seems likely to continue incidentally working.
You could also consider checking out the commit from before we deleted the cabal file.
There is also a stack-flavoured fork of the course at https://github.com/bitemyapp/fp-course . You could probably get haskell-ide-engine working with stack on their fork, and that kind of tooling might be more aligned with the goals their fork.

**Comment by wizzup** [comment]
Please update README too.

https://github.com/data61/fp-course/blob/master/README.markdown#learning-the-tools
