### ISSUE TITLE
optional vs foldOptional in Optional.hs

### ISSUE THREAD

**Issue by maxild** [data61/fp-course#385]
Would it make sense to rename `optional`

```haskell
-- NOTE: This is foldOptional (catamorphism)
optional ::
  (a -> b)
  -> b
  -> Optional a
  -> b
optional g _ (Full a) = g a
optional _ x Empty    = x
```

to `foldOptional`, and make some notes later on when using foldRight in List.hs about constructor replacement? Or is `optional` known to haskellers (`hoogle optional` didn't find the type above)

**Comment by endgame** [comment]
`Optional` is fp-course's name for `Maybe`. fp-course builds its own version of things so that students aren't confused when bits of the standard library leak in. Example: many functions over lists have been generalised in the standard libraries to a `Foldable` typeclass.

It is actually lists that are the exception. The common pattern is to name a catamorphism after its data type:

* `Data.Bool.bool` is the catamorphism for `Bool`
* `Data.Maybe.maybe` is the catamorphism for `Maybe` (what fp-course calls `Optional`)

`[]` doesn't have any letters in its name so it can't be lowercased, and I suspect the `foldl`/`foldr` naming (as they are called in the standard libraries) predates people realising that catamorphisms for other types are also really handy.

**Comment by maxild** [comment]
Thanks for the answer. Then `optional` makes perfect sense.

Is it correct that catamorphims for recursive types like trees, are still called foldSomething? They cannot be called `tree`. But unlike list (that only has right and left traversals), a tree/graph can be traversed in many ways. I guess the traversal/fold/reduce/transform must be called depth-first or bread-first or pre-order/in-order/post-order, and then it must be difficult to enforce a naming standard?

**Comment by endgame** [comment]
The catamorphism for a data type does constructor replacement, which means that if you call the catamorphism with the constructors as arguments, you should get the identity function as a result:

```haskell
foldr (:) [] = id (on lists)
bool False True = id (on Bool)
maybe Nothing Just = id (on Maybe)
```

So for a tree type, here's what you'd need:
```haskell
data Tree a = NilT | Node a (Tree a) (Tree a)

-- The convention of using a lowecase name is weaker for recursive types. The containers package has a "foldTree" function, for example.
-- Of the different tree traversals you suggested, only this implementation has the property that
-- foldTree NilT Node = id (on trees)
foldTree :: b -> (a -> b -> b -> b) -> Tree a -> b
foldTree z _ NilT = z
foldTree z f (Node a left right) = f a (foldTree z f left) (foldTree z f right)
```
